import pytest
import pandas as pd
from plotly.graph_objects import Figure
from components.plot_generator import create_px_figure


def test_create_px_figure_returns_figure_instance():
    """Test that create_px_figure returns a Figure instance for a valid plot type."""
    df = pd.DataFrame(
        {"Category": ["A", "B", "C", "A", "B", "C"], "Value": [10, 15, 7, 12, 18, 5]}
    )
    func_name = "bar"
    kwargs = {"x": "Category", "y": "Value", "color": "Category", "data_frame": df}

    fig = create_px_figure(func_name, df, kwargs)
    assert isinstance(fig, Figure), f"Expected Figure instance, got {type(fig)}"


def test_create_px_figure_bar_plot_structure():
    """Test that a bar plot generated by create_px_figure has the correct structure."""
    df = pd.DataFrame(
        {"Category": ["A", "B", "C", "A", "B", "C"], "Value": [10, 15, 7, 12, 18, 5]}
    )
    func_name = "bar"
    kwargs = {"x": "Category", "y": "Value", "color": "Category", "data_frame": df}

    fig = create_px_figure(func_name, df, kwargs)

    assert fig.data[0].x is not None, "X-axis data should not be None"
    assert fig.data[0].y is not None, "Y-axis data should not be None"
    assert (
        fig.layout.legend.title.text == "Category"
    ), "Legend title should match 'Category'"


def test_create_px_figure_scatter_plot_structure():
    """Test that a scatter plot generated by create_px_figure has the correct structure."""
    df = pd.DataFrame(
        {"Category": ["A", "B", "C", "A", "B", "C"], "Value": [10, 15, 7, 12, 18, 5]}
    )
    func_name = "scatter"
    kwargs = {"x": "Category", "y": "Value", "color": "Category", "data_frame": df}

    fig = create_px_figure(func_name, df, kwargs)

    assert fig.data[0].x is not None, "X-axis data should not be None"
    assert fig.data[0].y is not None, "Y-axis data should not be None"
    assert (
        fig.layout.legend.title.text == "Category"
    ), "Legend title should match 'Category'"


def test_create_px_figure_empty_dataframe_raises_value_error():
    """Test that create_px_figure raises a ValueError when given an empty DataFrame."""
    empty_df = pd.DataFrame()
    kwargs = {"x": "Category", "y": "Value", "data_frame": empty_df}

    with pytest.raises(ValueError):
        create_px_figure("bar", empty_df, kwargs)


def test_create_px_figure_invalid_function_name_raises_attribute_error():
    """Test that create_px_figure raises an AttributeError for an invalid function name."""
    df = pd.DataFrame(
        {"Category": ["A", "B", "C", "A", "B", "C"], "Value": [10, 15, 7, 12, 18, 5]}
    )
    with pytest.raises(AttributeError):
        create_px_figure("invalid_func", df, {"x": "Category", "y": "Value"})
