name: Test and Coverage Report

on:
  push:
#     branches:
#       - main
#   pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r src/tests/requirements.txt
        #   pip install pytest-cov

      - name: Run tests with coverage
        run: |
          pytest --cov-report=html --cov=src src/tests/
        #   pytest --cov-report=html term-missing --cov=src src/tests/
        #   pytest --cov=src --cov-report=html  # Adjust with your package name
        env:
          CI: true

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: htmlcov  # The directory pytest-cov saves HTML reports to

  push-coverage:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Download coverage report
        uses: actions/download-artifact@v3
        with:
          name: coverage-report
          path: coverage

      - name: Commit coverage report
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -B coverage-report
          mv coverage/htmlcov/* .  # Adjust path if needed
          git add .
          git commit -m "Update coverage report"
          git push -f origin coverage-report
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
