name: end-to-end tests

on: [push, pull_request]

jobs:
  pytest:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: browser-actions/setup-chrome@v1
      with:
          install-chromedriver: true
          install-dependencies: true
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
          python-version: '3.x'
    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
    - name: Run the app
      run: |
          python frontend/analytics/app.py &
    - name: Test with pytest
      run: |
          pip install pytest pytest-cov
          pip install selenium webdriver-manager
          pytest frontend/analytics/tests/end_to_end_tests
