name: formatting

on: [push, pull_request]

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Check code with black formatter
      uses: psf/black@stable
      with:
        options: "--check --verbose"
        jupyter: true
